# Generated by Django 4.2.19 on 2025-03-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_history', '0004_alter_patient_address_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prescriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
