# Generated by Django 4.2.19 on 2025-03-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_history', '0005_alter_patient_address_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
