# Generated by Django 4.2.19 on 2025-03-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_history', '0006_alter_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='description',
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
