# Generated by Django 4.2.19 on 2025-03-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_history', '0007_remove_patient_description_doctor_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
