# Generated by Django 4.2.19 on 2025-03-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_history', '0008_doctor_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prescriptions',
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('details', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_history.patient')),
            ],
        ),
    ]
