# Generated by Django 4.2.19 on 2025-03-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_history', '0011_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patient_history.patient'),
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
