# Generated by Django 4.2.19 on 2025-03-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_history', '0012_alter_prescription_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_history.patient'),
        ),
    ]
